definitions:
  models.TeamRPI:
    properties:
      name:
        type: string
      value:
        type: number
    type: object
  responses.HealthCheckResponse:
    properties:
      message:
        type: string
    type: object
  responses.VersionResponse:
    properties:
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: Check if the API is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthCheckResponse'
      summary: Health Check
      tags:
      - Admin
  /v1/rpi:
    get:
      consumes:
      - application/json
      description: Calculates the RPI rankings for all teams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TeamRPI'
            type: array
      summary: Examines the schedule and calculates the RPI rankings for all teams
      tags:
      - RPI
  /v1/version:
    get:
      consumes:
      - application/json
      description: Get the current version of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.VersionResponse'
      summary: Get the API's current version
      tags:
      - Admin
swagger: "2.0"
