# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.21'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: $GO_VERSION

    - name: Analyze Syntax
      uses: golangci/golangci-lint-action@v3

  test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: $GO_VERSION

    - name: Install Dependencies
      run: make deps

    - name: Test
      run: make test

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          ./junit.xml
      if: always()

  build:
    needs: [analyze, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: $GO_VERSION

    - name: Install Dependencies
      run: make deps

    - name: Analyze Syntax
      uses: golangci/golangci-lint-action@v3

    - name: Test
      run: make test

    - name: Build
      run: make build

  publish:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: $GO_VERSION
    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
