# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  workflow_dispatch: null

  push:
    branches:
      - '**'

env:
  GO_VERSION: 1.21

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go install go.uber.org/mock/mockgen@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate Mocks
        run: |
          pwd
          ls
          go generate ./...

      - name: Lint
        run: |
          pwd
          ls
          golangci-lint run ./...

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          pwd
          ls          
          go install go.uber.org/mock/mockgen@latest
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Generate Mocks
        run: go generate ./...

      - name: Test
        run: ginkgo --junit-report=junit.xml ./...

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit.xml'
          fail_on_failure: true
          require_tests: true
          annotate_notice: false
          detailed_summary: false

  Build:
    needs: [Analyze, Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -ldflags="-s -w" main.go

  Release:
    needs: [Build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set Git User
        run: |
          git config --global user.email "omar.crosby@gmail.com"
          git config --global user.name "Omar Crosby"

      - name: Run Semantic Release
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Deploy:
    needs: [Release]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_ORG: jediknights
      DOCKER_IMAGE_NAME: tds-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: read-version
        run: echo ::set-output name=VERSION::$(cat VERSION)

      - name: Build Docker Image
        run: |
          docker build -t $DOCKERHUB_ORG/$DOCKER_IMAGE_NAME:${{ steps.read-version.outputs.VERSION }} .

      - name: Tag Docker Image
        run: |
          docker tag $DOCKERHUB_ORG/$DOCKER_IMAGE_NAME:${{ steps.read-version.outputs.VERSION }} $DOCKERHUB_ORG/$DOCKER_IMAGE_NAME:latest

      - name: Push Docker Image
        run: |
          docker push $DOCKERHUB_ORG/$DOCKER_IMAGE_NAME:${{ steps.read-version.outputs.VERSION }}
          docker push $DOCKERHUB_ORG/$DOCKER_IMAGE_NAME:latest
