# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  workflow_dispatch: null

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.21

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Dependencies
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Lint
      run: golangci-lint run ./...

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Dependencies
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Test
      run: ginkgo --junit-report=junit.xml ./...

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        fail_on_failure: true
        require_tests: true
        annotate_notice: true
        detailed_summary: true

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          ./junit.xml
      if: always()

  Build:
    needs: [analyze, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Dependencies
      run: make deps

    - name: Build
      run: make build

  Publish:
    needs: build
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
