
name: Build Angular

on:
  push:
    paths:
    - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: client/dist/client
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Build Docker Image
        run: |
          docker build -t jediknights/ecnl-client:latest -t jediknights/ecnl-client:${{ github.sha }} ./client
